import { StyleSheet } from "react-native"
export const Style = StyleSheet.create({
    form:{
        fontSize:20,
        fontWeight:"bold",
        color:"#272829",
        textAlign:"center",
        borderWidth:2,
        borderRadius:12,
        borderColor:"red",
        marginVertical:10
    },
    formWhite:{
        fontSize:20,
        fontWeight:"bold",
        color:"#F3F8FF",
        textAlign:"center",
        borderWidth:2,
        borderRadius:12,
        borderColor:"#F3F8FF",
        marginVertical:10
    },
    btnBlack:{
        textAlign:"center",
        backgroundColor:"#040D12",
        color:"#F3F8FF",
        fontSize:22,
        padding:10,
        fontWeight:"bold",
        borderRadius:10,
        marginVertical:10
    },
    btnDelete:{
        textAlign:"center",
        backgroundColor:"red",
        color:"#F3F8FF",
        fontSize:22,
        padding:10,
        fontWeight:"bold",
        borderRadius:10,
        marginVertical:10
    },
    btnBlue:{
        textAlign:"center",
        fontSize:22,
        fontWeight:"bold",
        backgroundColor:"blue",
        color:"#F3F8FF",
        padding:10,
        borderRadius:10
    },
    centerView:{
        flex:1,
        marginHorizontal:"5%",
        justifyContent:"center",
    },
    radio:{
        fontSize:16,
        fontWeight:"bold",
     
    },
    radioTitle:{
        fontSize:18,
        fontWeight:"bold",
        color:"black"
    },
    title:{
        color:"#F3F8FF",
        textAlign:"center",
        fontWeight:"bold",
        fontSize:21,
        height:"auto",
        padding:10,
        // backgroundColor:"#032343"
        backgroundColor:"blue"
    },
    listStyle:{
        fontSize:18,
        color:"#F3F8FF",
        fontWeight:"bold",
        opacity:10
    }
})